### ISSUE TITLE
gem-mapper segmentation fault

### ISSUE THREAD

**Issue by t-pauli** [Chimera-tools/ChimPipe#16]
Hi,
I’m trying to run ChimPipe to find fusion transcripts and followed the user’s guide to install and run ChimPipe. Additionally, I set up a conda environment with all dependencies to run ChimPipe (see appended .yml-file). However, while executing Chimpipe I’m getting the following error in the log file *_firstMap.log:

> Running step: initial
> Fatal error (gt_output_file.c:334,gt_output_file_sorted_write_buffer_asynchronous)
> Output file. Error writing to to file
> 2021-05-10 16:36:39,948 ERROR: Process '/home/tpauli/Chimera_Tools/ChimPipe/bin/gemtools-1.7.1-i3/gem-mapper' finished with -11
> ERROR: Error while executing step initial : Execution failed!
> Cleaning up after failed step : initial
> Step initial failed after : 0:00:00
> An error occured while waiting for one the child processes: Process '/home/tpauli/Chimera_Tools/ChimPipe/bin/gemtools-1.7.1-i3/gem-mapper' finished with -11

When trying to execute gem-mapper from ChimPipe/bin/gemtools-1.7.1-i3/gem-mapper I am getting a Segmentation Fault error. So apparently this is where the problem lies. However, I was unable to get more information on this issue. 

Do you have any idea how to fix the problem, or at least narrow down what is going wrong?

I’m working on a cluster with Debian GNU/Linux 10 (buster) and 4.19.0-16-amd64 in case this is relevant.

Best wishes,
Thomas

[chimpipe.yml.zip](https://github.com/Chimera-tools/ChimPipe/files/6453053/chimpipe.yml.zip)

**Comment by sdjebali** [comment]
Hi,

A segmentation fault might indicate a memory (ram) issue.

on which genome are you using the tool and how much ram did you give to the process?

Thanks

⁣Télécharger BlueMail pour Android ​

Le 10 mai 2021 à 17:04, à 17:04, t-pauli ***@***.***> a écrit:

**Comment by t-pauli** [comment]
Hi,

thank you very much for your fast response. 

> on which genome are you using the tool 

I was using hg19 as reference genome and downloaded my reference files from here: https://chimpipe.readthedocs.io/en/latest/downloads.html

> how much ram did you give to the process?

I ran it with 8 threads with 14 GB RAM each, which should be more than enough, I suppose.

What is quite strange is that I also get a segmentation fault when I call gem-mapper with only the help option (gem-mapper -h).

**Comment by sdjebali** [comment]
Then this is definitely due to the environment
I will try to send you a yaml file that you can use

**Comment by sdjebali** [comment]
Hi,

Before trying with a new environment, we think it is possible the GEM binaries are not made for your architecture.

So could you please download the GEM core2 binaries from here
https://gemtools.github.io/
In the Downloads section you will find
GEM-Tools static binary bundle 1.7.1 for core2

please download that and then 
tar -xvzf GEMTools-static-core2-1.7.1.tar.gz 
cd gemtools-1.7.1-core2/bin/
./gem-rna-tools  -h
for example

do you still get a seg fault ?

if not then you would need to replace all the gem binaries at the top of the ChimPipe.sh script by those (in the section 5. Programs/Scripts Bin) 

Please let me know
Best,

**Comment by t-pauli** [comment]
Hi,

I also thought this might be a problem, but sadly using the core2 binaries doesn't make any difference to me. I also ran the command 

`python -c 'print ("i3 compatible" if set(["popcnt", "ssse3", "sse4_1", "sse4_2"]).issubset(set([f for sl in map(lambda x:x.split(), filter(lambda x:x.startswith("flags"), open("/proc/cpuinfo").readlines())) for f in sl])) else "No i3 support detected. Please use the core2 bundle")'`

and apparently my architecture should be compatible with the i3 binaries.

**Comment by t-pauli** [comment]
Small update: I copied the binary to a different server (a VM running SUSE Linux Enterprise Server 15 SP with 5.3.18-24.61-default lnux kernel and there it seems to work without any issues. Sadly that server does not serve any data analysis purpose, so I cannot run ChimPipe there. But the issue seems to lie in the architecture of the Debian server. While the kernel of the Debian server is an older version, I doubt this can be a problem. Maybe it's an administrative issue.

**Comment by sdjebali** [comment]
Unfortunately the problem is more likely due to the server being old than to an administrative issue I think...
Very sorry about that
