### ISSUE TITLE
Using python to round

### ISSUE THREAD

**Issue by messersc** [Chimera-tools/ChimPipe#3]
Hi,

I was able to use your tool on all our samples now. One tiny thing that I needed to fix was ChimPipe's use of python to round a number.
The problem was, that in my shell session, ```python``` was mapping to python 3, not 2.7.

So either you could use ```python2``` in the script, as I am not aware of any side effects to this or one could look into ```printf``` for rounding, which would be the cleaner solution in my humble opinion as it gets rid of the python2 dependency (well, I guess gemtools still uses it somewhere).

## Python2

```diff
 # 2. Set maximum number of mismatches == X% of the pair length 
 ################################################################
-nbMism=`echo $avMatesLen | awk -v percMism=$percMism '{avMatesLen=$1; nbMism=(avMatesLen*percMism)*2/100; print nbMism;}' | python -c "print int(round(float(raw_input())))"`
+nbMism=`echo $avMatesLen | awk -v percMism=$percMism '{avMatesLen=$1; nbMism=(avMatesLen*percMism)*2/100; print nbMism;}' | python2 -c "print int(round(float(raw_input())))"`
```

## printf

see http://unix.stackexchange.com/a/167059

```sh
echo 7 | LC_ALL=C xargs /usr/bin/printf "%.*f\n" 0
echo 7.684956 | LC_ALL=C xargs /usr/bin/printf "%.*f\n" 0
echo 7.184956 | LC_ALL=C xargs /usr/bin/printf "%.*f\n" 0
```

**Comment by brguez** [comment]
Hi Clemens, 

Thanks for the tip. We have already substituted the python command by printf. See latest commit. Also, it will be incorporated in the new release. 

Best, 
Bernardo
